import {
  Layers, HardDrive, Shield, Database, LayoutTemplate,
  SlidersHorizontal, MessageSquare, Workflow, CalendarClock,
  Mail, Key, UserCheck, Network, Flame, TerminalSquare,
  Activity, Server, Mic, Globe, Search as SearchIcon, GitBranch, Share2, LifeBuoy, Boxes, ClipboardList, Waypoints,
  Lock,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { Service } from '../types'

export interface ServiceMeta {
  /** Short name used in NavRail tooltips and tab labels */
  label: string
  /** Full name used in ServiceSelector cards */
  name: string
  /** Description paragraph in ServiceSelector cards */
  description: string
  /** Feature bullet points in ServiceSelector cards */
  features: string[]
  /** Hex color for NavRail icon background and active-state highlight */
  hex: string
  /** Lucide icon component (render as `<meta.icon size={n} />`) */
  icon: LucideIcon
  /** Tailwind class strings for ServiceSelector card styling */
  colors: {
    border: string
    icon: string
    dot: string
    text: string
  }
  /** 0-based position in the default ordered service list */
  order: number
}

export const SERVICE_CONFIG: Record<Service, ServiceMeta> = {
  sqs: {
    label: 'SQS',
    name: 'Simple Queue Service',
    description: 'Manage message queues, send and receive messages with full queue lifecycle management.',
    features: ['List & create queues', 'Send & poll messages', 'FIFO & Standard queues', 'Queue attributes & purge'],
    hex: '#0ea5e9',
    icon: Layers,
    colors: { border: 'hover:border-brand-500/50', icon: 'bg-brand-500/10 text-brand-500', dot: 'bg-brand-500', text: 'text-brand-500' },
    order: 0,
  },
  s3: {
    label: 'S3',
    name: 'Simple Storage Service',
    description: 'Browse buckets and objects, upload and download files, manage your object storage.',
    features: ['List & create buckets', 'Browse & upload objects', 'Download & delete files', 'Presigned URLs'],
    hex: '#10b981',
    icon: HardDrive,
    colors: { border: 'hover:border-emerald-500/50', icon: 'bg-emerald-500/10 text-emerald-500', dot: 'bg-emerald-500', text: 'text-emerald-500' },
    order: 1,
  },
  dynamodb: {
    label: 'DynamoDB',
    name: 'DynamoDB',
    description: 'Manage document tables, query records, and adjust high-performance schemaless structures.',
    features: ['List & create tables', 'Edit JSON items', 'Scan documents', 'Table metrics'],
    hex: '#8b5cf6',
    icon: Database,
    colors: { border: 'hover:border-violet-500/50', icon: 'bg-violet-500/10 text-violet-500', dot: 'bg-violet-500', text: 'text-violet-500' },
    order: 2,
  },
  lambda: {
    label: 'Lambda',
    name: 'AWS Lambda',
    description: 'Serverless compute service that lets you run code without provisioning or managing servers.',
    features: ['List & invoke functions', 'Create Zip packages', 'View Execution limits', 'Manage Handlers'],
    hex: '#8b5cf6',
    icon: TerminalSquare,
    colors: { border: 'hover:border-violet-500/50', icon: 'bg-violet-500/10 text-violet-500', dot: 'bg-violet-500', text: 'text-violet-500' },
    order: 3,
  },
  secretsmanager: {
    label: 'Secrets Manager',
    name: 'Secrets Manager',
    description: 'Securely store, retrieve, and manage sensitive information like API keys and credentials.',
    features: ['List & create secrets', 'View & edit secret values', 'Delete secrets', 'JSON & Text support'],
    hex: '#6366f1',
    icon: Shield,
    colors: { border: 'hover:border-indigo-500/50', icon: 'bg-indigo-500/10 text-indigo-500', dot: 'bg-indigo-500', text: 'text-indigo-500' },
    order: 4,
  },
  sns: {
    label: 'SNS',
    name: 'Simple Notification Service',
    description: 'Manage topics, publish messages, and handle subscriptions for pub/sub messaging.',
    features: ['List & create topics', 'Publish raw messages', 'Manage endpoints', 'View subscriptions'],
    hex: '#ec4899',
    icon: MessageSquare,
    colors: { border: 'hover:border-pink-500/50', icon: 'bg-pink-500/10 text-pink-500', dot: 'bg-pink-500', text: 'text-pink-500' },
    order: 5,
  },
  eventbridge: {
    label: 'EventBridge',
    name: 'EventBridge',
    description: 'Manage event buses, route events with rules, and map targets.',
    features: ['List & create buses', 'Manage rules & schedules', 'Map target routing', 'Send custom events'],
    hex: '#d946ef',
    icon: Workflow,
    colors: { border: 'hover:border-fuchsia-500/50', icon: 'bg-fuchsia-500/10 text-fuchsia-500', dot: 'bg-fuchsia-500', text: 'text-fuchsia-500' },
    order: 6,
  },
  cloudwatch: {
    label: 'CloudWatch',
    name: 'CloudWatch',
    description: 'Monitor logs, metrics, and alarms to gain actionable insights into your AWS resources.',
    features: ['Browse Log Groups', 'Log Stream tailing', 'View Alarms', 'Metric listing'],
    hex: '#06b6d4',
    icon: Activity,
    colors: { border: 'hover:border-cyan-500/50', icon: 'bg-cyan-500/10 text-cyan-500', dot: 'bg-cyan-500', text: 'text-cyan-500' },
    order: 7,
  },
  ssm: {
    label: 'Parameter Store',
    name: 'Parameter Store',
    description: 'Store, retrieve, and manage configuration data and secrets using hierarchical SSM parameters.',
    features: ['List & create parameters', 'String & SecureString types', 'Version history', 'Path-based hierarchy'],
    hex: '#14b8a6',
    icon: SlidersHorizontal,
    colors: { border: 'hover:border-teal-500/50', icon: 'bg-teal-500/10 text-teal-500', dot: 'bg-teal-500', text: 'text-teal-500' },
    order: 8,
  },
  kms: {
    label: 'KMS',
    name: 'Key Management Service',
    description: 'Create and manage cryptographic keys and control their use across a wide range of AWS services.',
    features: ['Create symmetric keys', 'Manage aliases', 'Enable/disable keys', 'Encrypt & decrypt tester'],
    hex: '#8b5cf6',
    icon: Key,
    colors: { border: 'hover:border-violet-500/50', icon: 'bg-violet-500/10 text-violet-500', dot: 'bg-violet-500', text: 'text-violet-500' },
    order: 9,
  },
  iam: {
    label: 'IAM',
    name: 'Identity and Access Management',
    description: 'Securely manage access to AWS services and resources by managing users, groups, and roles.',
    features: ['Manage Users', 'Manage User Groups', 'Manage Roles & Trusts', 'View Policies'],
    hex: '#f43f5e',
    icon: UserCheck,
    colors: { border: 'hover:border-rose-500/50', icon: 'bg-rose-500/10 text-rose-500', dot: 'bg-rose-500', text: 'text-rose-500' },
    order: 10,
  },
  sts: {
    label: 'STS',
    name: 'Security Token Service',
    description: 'Request temporary, limited-privilege credentials for IAM users or federated users.',
    features: ['Get Caller Identity', 'Assume Role', 'Session Token', 'Federation Token & Web Identity'],
    hex: '#eab308',
    icon: Key,
    colors: { border: 'hover:border-yellow-500/50', icon: 'bg-yellow-500/10 text-yellow-500', dot: 'bg-yellow-500', text: 'text-yellow-500' },
    order: 11,
  },
  apigw: {
    label: 'API Gateway',
    name: 'API Gateway',
    description: 'Create, publish, maintain, monitor, and secure APIs at any scale.',
    features: ['REST APIs', 'Resources & Methods', 'Integrations', 'Deployments & Stages'],
    hex: '#8b5cf6',
    icon: Network,
    colors: { border: 'hover:border-violet-500/50', icon: 'bg-violet-500/10 text-violet-500', dot: 'bg-violet-500', text: 'text-violet-500' },
    order: 12,
  },
  cloudformation: {
    label: 'CloudFormation',
    name: 'CloudFormation',
    description: 'Deploy and manage infrastructure stacks using templates, tracking resources and events.',
    features: ['List & create stacks', 'View resources & events', 'Deploy templates', 'Update & delete stacks'],
    hex: '#f97316',
    icon: LayoutTemplate,
    colors: { border: 'hover:border-orange-500/50', icon: 'bg-orange-500/10 text-orange-500', dot: 'bg-orange-500', text: 'text-orange-500' },
    order: 13,
  },
  ses: {
    label: 'SES',
    name: 'Simple Email Service',
    description: 'Verify identities and send formatted emails to test your messaging flows.',
    features: ['Verify emails & domains', 'Send text & HTML emails', 'View identity status', 'Check send limits'],
    hex: '#0ea5e9',
    icon: Mail,
    colors: { border: 'hover:border-sky-500/50', icon: 'bg-sky-500/10 text-sky-500', dot: 'bg-sky-500', text: 'text-sky-500' },
    order: 14,
  },
  firehose: {
    label: 'Firehose',
    name: 'Kinesis Firehose',
    description: 'Load streaming data into data lakes, data stores, and analytics services.',
    features: ['List & create streams', 'Describe configurations', 'Put test records', 'S3 Destinations'],
    hex: '#f97316',
    icon: Flame,
    colors: { border: 'hover:border-orange-500/50', icon: 'bg-orange-500/10 text-orange-500', dot: 'bg-orange-500', text: 'text-orange-500' },
    order: 15,
  },
  kinesis: {
    label: 'Kinesis',
    name: 'Kinesis Streams',
    description: 'Collect and process large streams of data records in real time with high throughput and low latency.',
    features: ['List & create streams', 'Shard management', 'Retention policies', 'Throughput monitoring'],
    hex: '#f59e0b',
    icon: Activity,
    colors: { border: 'hover:border-amber-500/50', icon: 'bg-amber-500/10 text-amber-500', dot: 'bg-amber-500', text: 'text-amber-500' },
    order: 16,
  },
  redshift: {
    label: 'Redshift',
    name: 'Amazon Redshift',
    description: 'Fast, fully managed data warehouse that makes it simple and cost-effective to analyze all your data.',
    features: ['Cluster management', 'Node configuration', 'Database provisioning', 'Public/Private access'],
    hex: '#ef4444',
    icon: Database,
    colors: { border: 'hover:border-red-500/50', icon: 'bg-red-500/10 text-red-500', dot: 'bg-red-500', text: 'text-red-500' },
    order: 17,
  },
  opensearch: {
    label: 'OpenSearch',
    name: 'OpenSearch',
    description: 'Managed search and analytics engine for real-time log analytics, full-text search, and data visualization.',
    features: ['Domain management', 'Index management', 'Document search & indexing', 'Cluster health'],
    hex: '#a855f7',
    icon: SearchIcon,
    colors: { border: 'hover:border-purple-500/50', icon: 'bg-purple-500/10 text-purple-400', dot: 'bg-purple-500', text: 'text-purple-400' },
    order: 18,
  },
  ec2: {
    label: 'EC2',
    name: 'Elastic Compute Cloud',
    description: 'Scalable virtual computing environment to launch and manage instances, volumes, and networking.',
    features: ['Launch & manage instances', 'Key pairs & security groups', 'VPCs & subnets', 'EBS volumes'],
    hex: '#f97316',
    icon: Server,
    colors: { border: 'hover:border-orange-500/50', icon: 'bg-orange-500/10 text-orange-500', dot: 'bg-orange-500', text: 'text-orange-500' },
    order: 19,
  },
  transcribe: {
    label: 'Transcribe',
    name: 'Amazon Transcribe',
    description: 'Automatic speech recognition service that converts audio and video files to text transcripts.',
    features: ['Start transcription jobs', 'List & monitor jobs', 'View transcript output', 'Delete jobs'],
    hex: '#3b82f6',
    icon: Mic,
    colors: { border: 'hover:border-blue-500/50', icon: 'bg-blue-500/10 text-blue-500', dot: 'bg-blue-500', text: 'text-blue-500' },
    order: 20,
  },
  scheduler: {
    label: 'Scheduler',
    name: 'EB Scheduler',
    description: 'Create one-time or recurring schedules that trigger targets on flexible schedules.',
    features: ['Schedule groups', 'Rate & cron schedules', 'One-time (at) schedules', 'Enable/disable schedules'],
    hex: '#f59e0b',
    icon: CalendarClock,
    colors: { border: 'hover:border-amber-500/50', icon: 'bg-amber-500/10 text-amber-500', dot: 'bg-amber-500', text: 'text-amber-500' },
    order: 21,
  },
  route53: {
    label: 'Route 53',
    name: 'Route 53',
    description: 'Scalable DNS and domain name management service for routing end users to your applications.',
    features: ['Hosted zone management', 'DNS record management', 'Health checks', 'Public & private zones'],
    hex: '#60a5fa',
    icon: Globe,
    colors: { border: 'hover:border-blue-400/50', icon: 'bg-blue-400/10 text-blue-400', dot: 'bg-blue-400', text: 'text-blue-400' },
    order: 22,
  },
  acm: {
    label: 'Certificate Manager',
    name: 'Certificate Manager',
    description: 'Request, manage, and deploy SSL/TLS certificates for your domains and AWS resources.',
    features: ['Request & import certificates', 'DNS & Email validation', 'View certificate details', 'Manage SANs & tags'],
    hex: '#14b8a6',
    icon: Shield,
    colors: { border: 'hover:border-teal-500/50', icon: 'bg-teal-500/10 text-teal-500', dot: 'bg-teal-500', text: 'text-teal-500' },
    order: 23,
  },
  swf: {
    label: 'SWF',
    name: 'Simple Workflow Service',
    description: 'Coordinate distributed application components with workflow executions, activity tasks, and decision logic.',
    features: ['Manage workflow domains', 'Register workflow & activity types', 'Start & monitor executions', 'Signal & terminate workflows'],
    hex: '#22c55e',
    icon: GitBranch,
    colors: { border: 'hover:border-green-500/50', icon: 'bg-green-500/10 text-green-500', dot: 'bg-green-500', text: 'text-green-500' },
    order: 24,
  },
  sfn: {
    label: 'SFN',
    name: 'Step Functions',
    description: 'Visually compose and orchestrate serverless workflows using state machines, activities, and SDK integrations.',
    features: ['Create & manage state machines', 'Start & monitor executions', 'View execution history', 'Manage activities'],
    hex: '#84cc16',
    icon: Share2,
    colors: { border: 'hover:border-lime-500/50', icon: 'bg-lime-500/10 text-lime-500', dot: 'bg-lime-500', text: 'text-lime-500' },
    order: 25,
  },
  support: {
    label: 'Support',
    name: 'AWS Support',
    description: 'Manage AWS Support cases and view Trusted Advisor checks to optimize your AWS environment.',
    features: ['Create & manage cases', 'Resolve support cases', 'Trusted Advisor checks', 'Refresh check status'],
    hex: '#0ea5e9',
    icon: LifeBuoy,
    colors: { border: 'hover:border-sky-500/50', icon: 'bg-sky-500/10 text-sky-500', dot: 'bg-sky-500', text: 'text-sky-500' },
    order: 26,
  },
  r53resolver: {
    label: 'R53 Resolver',
    name: 'Route 53 Resolver',
    description: 'Manage DNS resolution between VPCs and on-premises networks with resolver endpoints, rules, and DNS Firewall.',
    features: ['Inbound & outbound endpoints', 'Resolver rules & VPC associations', 'Firewall rule groups & rules', 'Firewall domain lists'],
    hex: '#60a5fa',
    icon: Waypoints,
    colors: { border: 'hover:border-blue-400/50', icon: 'bg-blue-400/10 text-blue-400', dot: 'bg-blue-400', text: 'text-blue-400' },
    order: 29,
  },
  awsconfig: {
    label: 'Config',
    name: 'AWS Config',
    description: 'Assess, audit, and evaluate configurations of your AWS resources with configuration recorders, delivery channels, and config rules.',
    features: ['Configuration recorders', 'Delivery channels', 'Config rules & compliance', 'Resource discovery'],
    hex: '#f59e0b',
    icon: ClipboardList,
    colors: { border: 'hover:border-amber-500/50', icon: 'bg-amber-500/10 text-amber-500', dot: 'bg-amber-500', text: 'text-amber-500' },
    order: 28,
  },
  s3control: {
    label: 'S3 Control',
    name: 'S3 Control',
    description: 'Manage S3 access points, multi-region access points, and account-level public access block settings.',
    features: ['Create & manage access points', 'Multi-region access points', 'Access point policies', 'Account public access block'],
    hex: '#0d9488',
    icon: Lock,
    colors: { border: 'hover:border-teal-600/50', icon: 'bg-teal-600/10 text-teal-500', dot: 'bg-teal-600', text: 'text-teal-500' },
    order: 30,
  },
  resourcegroups: {
    label: 'Resource Groups',
    name: 'Resource Groups',
    description: 'Organize and manage AWS resources by grouping them using tag-based or CloudFormation stack queries.',
    features: ['Create & manage groups', 'Tag-based resource queries', 'Tag Explorer across resources', 'Tag sync tasks'],
    hex: '#f97316',
    icon: Boxes,
    colors: { border: 'hover:border-orange-500/50', icon: 'bg-orange-500/10 text-orange-500', dot: 'bg-orange-500', text: 'text-orange-500' },
    order: 27,
  },
}

/** All services in their default display order. */
export const ALL_SERVICES_ORDERED: Service[] = (
  Object.entries(SERVICE_CONFIG) as [Service, ServiceMeta][]
).sort(([, a], [, b]) => a.order - b.order).map(([svc]) => svc)
